CREATE DATABASE  hotel_alura;

USE hotel_alura;

CREATE TABLE USERS(
    id INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    USUARIO VARCHAR(50),
    password VARCHAR(250),
    PRIMARY KEY(id)
);


CREATE TABLE huespedes(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    F_NACIMIENTO DATE,
    NACIONALIDAD VARCHAR(70),
    TELEFONO VARCHAR(12),
    ID_RESERVA INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID)

);



CREATE TABLE RESERVAS(
    ID INT AUTO_INCREMENT NOT NULL,
    FECHA_ENTRADA DATE ,
    FECHA_SALIDA DATE,
    VALOR FLOAT NOT NULL,
    FORMA_PAGO VARCHAR(55),
    PRIMARY KEY(ID)
);


CREATE TABLE SESSION(
    ID_USUARIO INT NOT NULL,
    CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USERS(ID)
);

CREATE TABLE PRECIO_RESERVAS(
    ID INT AUTO_INCREMENT NOT NULL,
    precio FLOAT NOT NULL,
    PRIMARY KEY(ID)

);

INSERT INTO hotel_alura.precio_reservas (precio_reservas.precio) values (12);

select * from hotel_alura.precio_reservas;

